# Generated by Django 3.1.6 on 2021-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0002_auto_20210217_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=240),
        ),
    ]
