# Generated by Django 3.1.6 on 2021-02-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0002_activity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ManyToManyField(to='gjorno.Category'),
        ),
    ]
