# Generated by Django 3.1.6 on 2021-02-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0002_auto_20210217_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=240),
        ),
    ]
