# Generated by Django 3.1.6 on 2021-02-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0003_auto_20210209_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='category',
            new_name='categories',
        ),
    ]
