# Generated by Django 3.1.6 on 2021-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0003_auto_20210309_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ingress',
            field=models.TextField(default='none', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(),
        ),
    ]
