# Generated by Django 3.1.6 on 2021-03-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0004_auto_20210310_1518'),
        ('gjorno', '0004_profile_is_organization'),
    ]

    operations = [
    ]
