# Generated by Django 3.1.6 on 2021-03-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0005_registration'),
        ('gjorno', '0005_merge_20210310_2356'),
    ]

    operations = [
    ]
