# Generated by Django 3.1.6 on 2021-03-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0007_auto_20210315_1045'),
        ('gjorno', '0003_auto_20210225_2025'),
    ]

    operations = [
    ]
