# Generated by Django 3.1.6 on 2021-03-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0007_auto_20210315_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
