# Generated by Django 3.1.6 on 2021-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
