# Generated by Django 3.1.6 on 2021-03-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0008_merge_20210316_0844'),
        ('gjorno', '0007_auto_20210315_0857'),
    ]

    operations = [
    ]
