# Generated by Django 3.1.6 on 2021-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0010_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/activities/'),
        ),
    ]
