# Generated by Django 3.1.6 on 2021-03-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0011_auto_20210321_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/gallery'),
        ),
    ]
