# Generated by Django 3.1.6 on 2021-03-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0012_auto_20210321_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/gallery/'),
        ),
    ]
