# Generated by Django 3.1.6 on 2021-03-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0013_auto_20210321_1019'),
        ('gjorno', '0009_auto_20210321_0949'),
    ]

    operations = [
    ]
