# Generated by Django 3.1.6 on 2021-03-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0013_auto_20210321_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Mid'), (3, 'High')], null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
