# Generated by Django 3.1.6 on 2021-03-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0008_favorite'),
        ('gjorno', '0017_auto_20210321_2113'),
        ('gjorno', '0014_auto_20210324_0846'),
    ]

    operations = [
    ]
