# Generated by Django 3.1.6 on 2021-03-24 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gjorno', '0017_auto_20210321_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='users_viewed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
