# Generated by Django 3.1.6 on 2021-03-24 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0018_merge_20210324_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
