# Generated by Django 3.1.6 on 2021-03-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0019_auto_20210324_1136'),
        ('gjorno', '0018_activity_users_viewed'),
    ]

    operations = [
    ]
