# Generated by Django 3.1.6 on 2021-03-24 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gjorno', '0020_merge_20210324_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='users_viewed',
            field=models.ManyToManyField(blank=True, related_name='activities_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
