# Generated by Django 3.1.6 on 2021-03-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0021_auto_20210324_1500'),
        ('gjorno', '0020_auto_20210326_1357'),
    ]

    operations = [
    ]
