# Generated by Django 3.1.6 on 2021-03-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0022_merge_20210328_1919'),
        ('gjorno', '0022_merge_20210328_1912'),
    ]

    operations = [
    ]
