# Generated by Django 3.1.6 on 2021-03-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0023_merge_20210329_1137'),
        ('gjorno', '0020_log'),
    ]

    operations = [
    ]
