# Generated by Django 3.1.6 on 2021-04-03 22:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0024_merge_20210329_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#EEEEEE', max_length=18),
        ),
    ]
