# Generated by Django 3.1.6 on 2021-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0026_auto_20210406_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
